# Generated by Django 5.1.5 on 2025-01-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_p', '0002_remove_cart_total_alter_order_total_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='bank',
            name='money',
            field=models.IntegerField(default=1000),
        ),
    ]
