# Generated by Django 5.1.5 on 2025-01-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_p', '0003_remove_product_image_alter_bank_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
